# Generated by Django 5.1.4 on 2025-12-09 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('repo_url', models.URLField(help_text='Gitea 仓库 HTTPS URL，如 https://gitea.dhr2333.cn/beancount-trans/{user_id}-beancount.git')),
                ('repo_name', models.CharField(help_text='仓库名称，如 {user_id}-beancount', max_length=200)),
                ('gitea_repo_id', models.IntegerField(help_text='Gitea 仓库 ID，用于 API 调用')),
                ('created_with_template', models.BooleanField(default=True, help_text='是否基于模板创建：True=基于模板，False=空仓库')),
                ('deploy_key_id', models.IntegerField(blank=True, help_text='Gitea Deploy Key ID', null=True)),
                ('deploy_key_private', models.TextField(help_text='Deploy Key 私钥（加密存储）')),
                ('deploy_key_public', models.TextField(help_text='Deploy Key 公钥')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='最后一次从仓库拉取时间', null=True)),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('syncing', '同步中'), ('success', '成功'), ('failed', '失败')], default='pending', help_text='同步状态', max_length=20)),
                ('sync_error', models.TextField(blank=True, help_text='最后一次同步错误信息')),
                ('owner', models.OneToOneField(help_text='仓库所有者', on_delete=django.db.models.deletion.CASCADE, related_name='git_repo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Git 仓库',
                'verbose_name_plural': 'Git 仓库',
                'db_table': 'git_repository',
            },
        ),
    ]
