# Generated by Django 5.1.4 on 2025-12-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitrepository',
            name='repo_url',
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='repo_name',
            field=models.CharField(help_text='仓库名称，如 {uuid}-assets', max_length=200),
        ),
    ]
