# Generated by Django 5.2.10 on 2026-03-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_repository', '0002_remove_gitrepository_repo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='default_branch',
            field=models.CharField(default='main', help_text='默认同步分支', max_length=100),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='external_full_name',
            field=models.CharField(blank=True, default='', help_text='外部仓库全名，如 owner/repo，用于 webhook 匹配', max_length=255),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='provider',
            field=models.CharField(choices=[('gitea_hosted', '平台托管 Gitea'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('other', '其他')], default='gitea_hosted', help_text='远程代码托管平台', max_length=20),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='remote_ssh_url',
            field=models.CharField(blank=True, default='', help_text='远程仓库 SSH 地址（用于 clone/pull）', max_length=500),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='setup_mode',
            field=models.CharField(choices=[('create', '创建远程'), ('link', '关联远程')], default='create', help_text='启用 Git 时的模式：create=创建远程，link=关联已有远程', max_length=20),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Webhook 验签密钥（每仓独立）', max_length=255),
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='gitea_repo_id',
            field=models.IntegerField(blank=True, help_text='Gitea 仓库 ID，用于 API 调用', null=True),
        ),
    ]
