# Generated by Django 6.0.5 on 2026-09-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_repository', '0003_gitrepository_default_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitrepository',
            name='provider',
            field=models.CharField(choices=[('gitea_hosted', '平台托管 Gitea'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('gogs', 'Gogs'), ('other', '其他')], default='gitea_hosted', help_text='远程代码托管平台', max_length=20),
        ),
    ]
