# FROM python:3.12-slim AS builder
FROM python:3.12-alpine AS builder
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn \
    PIP_DEFAULT_TIMEOUT=600 \
    PIP_RETRIES=5
WORKDIR /build
COPY requirements.txt .
COPY zh_core_web_md-3.8.0-py3-none-any.whl .
RUN apk add --no-cache --virtual .build-deps \
    build-base \
    python3-dev \
    linux-headers \
    && pip install --upgrade pip \
    && pip install --no-cache-dir --user wheel uwsgi \
    && pip install --no-cache-dir --user zh_core_web_md-3.8.0-py3-none-any.whl \
    && pip install --no-cache-dir --user -r requirements.txt \
    && apk del .build-deps

# 第二阶段：生产镜像
# FROM python:3.12-slim
FROM python:3.12-alpine
LABEL maintainer="daihaorui <Dai_Haorui@163.com>"
ENV PYTHONUNBUFFERED=1 \
    PATH="/root/.local/bin:${PATH}"
WORKDIR /code/beancount-trans/
RUN apk add --no-cache libstdc++
COPY --from=builder /root/.local /root/.local
COPY bin ./bin
COPY conf ./conf
COPY logs ./logs
COPY translate ./translate
COPY manage.py ./manage.py
# COPY static ./static
# COPY collectstatic ./collectstatic
COPY mydemo ./mydemo
COPY templates ./templates
RUN chmod +x /code/beancount-trans/bin/docker_start.sh
ENTRYPOINT ["/code/beancount-trans/bin/docker_start.sh"]