# FROM python:3.11.6-alpine as production-stage
FROM python:3.12.3 AS production-stage
LABEL maintainer="daihaorui <Dai_Haorui@163.com>"
ENV PYTHONUNBUFFERED=1
WORKDIR /code/beancount-trans/

COPY . .
RUN pip install --upgrade pip
RUN pip install setuptools wheel
RUN pip install uwsgi
RUN pip install --default-timeout=600 -r requirements.txt

# RUN chmod +x /code/beancount-trans/bin/wait-for-it.sh /code/beancount-trans/bin/docker_start.sh
# ENTRYPOINT ["/code/beancount-trans/bin/wait-for-it.sh","beancount-trans-mysql:3306","--","/code/beancount-trans/bin/docker_start.sh"]
RUN chmod +x /code/beancount-trans/bin/docker_start.sh
ENTRYPOINT ["/code/beancount-trans/bin/docker_start.sh"]