# Generated by Django 6.0.5 on 2026-06-17 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('message_id', models.UUIDField()),
                ('rating', models.CharField(choices=[('like', '喜欢'), ('dislike', '不喜欢')], max_length=8)),
                ('user_message', models.TextField()),
                ('assistant_reply', models.TextField()),
                ('queries', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '助手回复反馈',
                'verbose_name_plural': '助手回复反馈',
                'indexes': [models.Index(fields=['user', 'rating'], name='assistant_a_user_id_33980a_idx'), models.Index(fields=['created'], name='assistant_a_created_3ed6bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'message_id'), name='assistant_feedback_user_message_unique')],
            },
        ),
    ]
