# Generated by Django 6.0.5 on 2026-09-27 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_chatmessage_generation_status'),
        ('authentication', '0003_personalaccesstoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='shared_binding_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='会话纳入的共享账本绑定'),
        ),
        migrations.CreateModel(
            name='SharedLedgerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, default='', max_length=64, verbose_name='备注')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ledger_bindings', to=settings.AUTH_USER_MODEL, verbose_name='接收方')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_bindings', to='authentication.personalaccesstoken', verbose_name='访问令牌')),
            ],
            options={
                'verbose_name': '共享账本绑定',
                'verbose_name_plural': '共享账本绑定',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['recipient'], name='assistant_s_recipie_ac675b_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'token'), name='shared_ledger_binding_recipient_token_unique')],
            },
        ),
    ]
