"""
解析结果直接写入账本接口测试

POST /api/translate/write-collect

- 语法校验通过后追加写入 trans/collect.bean（保留注释头与已有内容，补齐 include）；
- 任一条目语法错误则整批拒绝、不写入；
- 必须登录（匿名 401）。
"""
from pathlib import Path

import pytest
from django.conf import settings
from rest_framework import status
from rest_framework.test import APIClient

from project.utils.file import BeanFileManager

HEADER = (
    '; Trans directory - Auto-generated includes\n'
    '; This file is automatically generated by the platform\n\n'
)
EXISTING = (
    '2025-01-01 * "已有" "历史条目"\n'
    '    Expenses:Old  1.00 CNY\n'
    '    Assets:Old  -1.00 CNY\n\n'
)
VALID_DIRECTIVE = (
    '2025-01-20 * "测试商户" "测试交易"\n'
    '    Expenses:Test  100.00 CNY\n'
    '    Assets:Test  -100.00 CNY'
)
INVALID_DIRECTIVE = 'this is not a beancount directive'


@pytest.fixture
def temp_assets(tmp_path, monkeypatch):
    """把 ASSETS_BASE_PATH 指向临时目录，隔离账本写入。"""
    base = tmp_path / 'Assets'
    base.mkdir()
    monkeypatch.setattr(settings, 'ASSETS_BASE_PATH', str(base))
    return base


def _collect_path(user):
    return Path(BeanFileManager.get_collect_bean_path(user))


def _prepare_ledger(user):
    """预置带注释头与历史条目的 collect.bean，返回其内容。"""
    collect_path = _collect_path(user)
    collect_path.parent.mkdir(parents=True, exist_ok=True)
    collect_path.write_text(HEADER + EXISTING, encoding='utf-8')
    return collect_path


@pytest.mark.django_db
class TestWriteCollectView:
    """POST /api/translate/write-collect"""

    def setup_method(self):
        self.client = APIClient()

    def test_write_appends_to_collect_bean(self, user, temp_assets):
        """合法条目追加写入 collect.bean，保留注释头与已有内容"""
        self.client.force_authenticate(user=user)
        collect_path = _prepare_ledger(user)

        response = self.client.post(
            '/api/translate/write-collect',
            {'entries': [{'uuid': 'entry-1', 'directive': VALID_DIRECTIVE}]},
            format='json',
        )

        assert response.status_code == status.HTTP_200_OK
        assert response.data == {
            'message': '写入成功',
            'entry_count': 1,
            'bean': 'trans/collect.bean',
        }

        text = collect_path.read_text(encoding='utf-8')
        assert text.startswith(HEADER)
        assert EXISTING in text
        assert 'Expenses:Test  100.00 CNY' in text

        # include 已补齐
        main_path = Path(BeanFileManager.get_trans_main_bean_path(user))
        assert 'include "collect.bean"' in main_path.read_text(encoding='utf-8')

    def test_write_syntax_error_rejects_all(self, user, temp_assets):
        """存在语法错误时整批拒绝，不写入任何条目"""
        self.client.force_authenticate(user=user)
        collect_path = _prepare_ledger(user)
        before = collect_path.read_text(encoding='utf-8')

        response = self.client.post(
            '/api/translate/write-collect',
            {
                'entries': [
                    {'uuid': 'entry-ok', 'directive': VALID_DIRECTIVE},
                    {'uuid': 'entry-bad', 'directive': INVALID_DIRECTIVE},
                ]
            },
            format='json',
        )

        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert 'Beancount 语法错误' in response.data['error']
        error_entry = response.data['error_entries'][0]
        assert error_entry['uuid'] == 'entry-bad'
        assert error_entry['index'] == 1
        assert error_entry['error_message']

        assert collect_path.read_text(encoding='utf-8') == before

    def test_write_without_entries_rejected(self, user, temp_assets):
        """缺少 entries / 无有效指令时返回 400"""
        self.client.force_authenticate(user=user)
        _prepare_ledger(user)

        missing = self.client.post('/api/translate/write-collect', {}, format='json')
        assert missing.status_code == status.HTTP_400_BAD_REQUEST
        assert missing.data['error'] == '缺少必要参数：entries'

        blank = self.client.post(
            '/api/translate/write-collect',
            {'entries': [{'uuid': 'entry-1', 'directive': '   '}]},
            format='json',
        )
        assert blank.status_code == status.HTTP_400_BAD_REQUEST
        assert blank.data['error'] == '没有可写入的条目'

    def test_write_anonymous_rejected(self, temp_assets):
        """匿名（未登录）写入返回 401"""
        response = self.client.post(
            '/api/translate/write-collect',
            {'entries': [{'uuid': 'entry-1', 'directive': VALID_DIRECTIVE}]},
            format='json',
        )

        assert response.status_code == status.HTTP_401_UNAUTHORIZED
