# Generated by Django 5.1.4 on 2025-09-23 08:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='货币代码', max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message="货币必须以大写字母开头，以大写字母/数字结尾，并且只能包含 [A-Z0-9'._-]", regex="^[A-Z][A-Z0-9\\'._-]{0,22}([A-Z0-9])?$")], verbose_name='货币代码')),
                ('name', models.CharField(max_length=32, verbose_name='货币名称')),
            ],
            options={
                'verbose_name': '货币',
                'verbose_name_plural': '货币',
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account'], 'verbose_name': '账本账户', 'verbose_name_plural': '账本账户'},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account', 'owner')},
        ),
        migrations.AddField(
            model_name='account',
            name='enable',
            field=models.BooleanField(default=True, help_text='启用状态', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父账户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account_config.account', verbose_name='父账户'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.CharField(help_text='账户路径', max_length=128, verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(help_text='属主', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='属主'),
        ),
        migrations.AddField(
            model_name='account',
            name='currencies',
            field=models.ManyToManyField(blank=True, help_text='货币', to='account_config.currency', verbose_name='货币'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='note',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
    ]
