# Generated by Django 5.1.4 on 2025-09-24 07:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0002_currency_alter_account_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='owner',
            field=models.ForeignKey(default=1, help_text='属主', on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL, verbose_name='属主'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='货币代码', max_length=24, validators=[django.core.validators.RegexValidator(message="货币必须以大写字母开头，以大写字母/数字结尾，并且只能包含 [A-Z0-9'._-]", regex="^[A-Z][A-Z0-9\\'._-]{0,22}([A-Z0-9])?$")], verbose_name='货币代码'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'owner')},
        ),
    ]
