# Generated by Django 5.1.4 on 2025-10-07 08:06

from django.db import migrations


def safe_remove_currency_tables(apps, schema_editor):
    """安全地删除Currency相关的表（如果存在）"""
    with schema_editor.connection.cursor() as cursor:
        # 删除account_currencies多对多表（如果存在）
        cursor.execute("""
            DROP TABLE IF EXISTS account_config_account_currencies CASCADE;
        """)
        # 删除Currency表（如果存在）
        cursor.execute("""
            DROP TABLE IF EXISTS account_config_currency CASCADE;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0003_currency_owner_alter_currency_code_and_more'),
        ('maps', '0009_convert_currency_to_charfield'),
    ]

    operations = [
        # 先删除字段，这会正确更新Django的迁移状态
        migrations.RemoveField(
            model_name='account',
            name='currencies',
        ),
        # 然后删除模型
        migrations.DeleteModel(
            name='Currency',
        ),
        # 最后安全地清理数据库表（如果还存在的话）
        migrations.RunPython(safe_remove_currency_tables, migrations.RunPython.noop),
    ]
