# Generated by Django 5.1.4 on 2025-10-10 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0004_remove_account_currencies_delete_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='模板名称', max_length=32)),
                ('description', models.TextField(blank=True, help_text='模板描述')),
                ('is_public', models.BooleanField(default=False, help_text='是否公开')),
                ('is_official', models.BooleanField(default=False, help_text='是否官方')),
                ('version', models.CharField(blank=True, default='1.0.0', help_text='版本号', max_length=16)),
                ('update_notes', models.TextField(blank=True, help_text='更新说明', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '账户模板',
                'verbose_name_plural': '账户模板',
                'db_table': 'account_template',
            },
        ),
        migrations.CreateModel(
            name='AccountTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account_path', models.CharField(help_text='账户路径', max_length=128)),
                ('enable', models.BooleanField(default=True, help_text='默认启用状态')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account_config.accounttemplate')),
            ],
            options={
                'verbose_name': '账户模板项',
                'verbose_name_plural': '账户模板项',
                'db_table': 'account_template_item',
            },
        ),
        migrations.AddConstraint(
            model_name='accounttemplate',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_account_template_per_user'),
        ),
        migrations.AddConstraint(
            model_name='accounttemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'account_path'), name='unique_account_per_template'),
        ),
    ]
