# Generated by Django 5.1.4 on 2026-01-14 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0005_remove_account_currencies_accounttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父账户', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='account_config.account', verbose_name='父账户'),
        ),
    ]
