# Generated by Django 5.2.10 on 2026-01-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0007_account_reconciliation_cycle_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttemplateitem',
            name='reconciliation_cycle_interval',
            field=models.PositiveIntegerField(blank=True, help_text='每隔多少个周期单位执行一次对账', null=True, verbose_name='对账周期间隔'),
        ),
        migrations.AddField(
            model_name='accounttemplateitem',
            name='reconciliation_cycle_unit',
            field=models.CharField(blank=True, choices=[('days', '天'), ('weeks', '周'), ('months', '月'), ('years', '年')], help_text='对账周期单位：天/周/月/年', max_length=10, null=True, verbose_name='对账周期单位'),
        ),
    ]
