# Generated by Django 5.2.10 on 2026-03-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0008_accounttemplateitem_reconciliation_cycle_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, default='', help_text='描述', max_length=256, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='accounttemplateitem',
            name='description',
            field=models.CharField(blank=True, default='', help_text='描述', max_length=256, verbose_name='描述'),
        ),
    ]
