# Generated by Django 4.2.1 on 2023-07-31 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
