# Generated by Django 4.2.1 on 2023-07-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets_map',
            options={'verbose_name': '收入映射', 'verbose_name_plural': '收入映射'},
        ),
        migrations.AlterField(
            model_name='assets_map',
            name='full',
            field=models.CharField(help_text='账户名称', max_length=16),
        ),
        migrations.AlterField(
            model_name='assets_map',
            name='income',
            field=models.CharField(default='Income:Other', help_text='收入账户', max_length=64),
        ),
        migrations.AlterField(
            model_name='assets_map',
            name='key',
            field=models.CharField(help_text='关键字', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='expense_map',
            name='classification',
            field=models.CharField(help_text='归类', max_length=16),
        ),
        migrations.AlterField(
            model_name='expense_map',
            name='expend',
            field=models.CharField(default='Expenses:Other', help_text='支出账户', max_length=64),
        ),
        migrations.AlterField(
            model_name='expense_map',
            name='payee',
            field=models.CharField(help_text='商家', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='expense_map',
            name='payee_order',
            field=models.IntegerField(default=100, help_text='优先级'),
        ),
        migrations.AlterField(
            model_name='expense_map',
            name='tag',
            field=models.CharField(help_text='标签', max_length=16),
        ),
        migrations.AlterModelTable(
            name='assets_map',
            table='translate_assets_map',
        ),
    ]
