# Generated by Django 4.1.1 on 2023-05-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_mycmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
