# Generated by Django 4.2.3 on 2023-09-18 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('translate', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payee_order',
        ),
    ]
