# Generated by Django 4.1.1 on 2023-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('translate', '0004_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='payee',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
