# Generated by Django 5.1.7 on 2025-03-20 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_remove_expense_classification_remove_expense_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(default='*', max_length=1)),
                ('show_note', models.BooleanField(default=True)),
                ('show_tag', models.BooleanField(default=True)),
                ('show_time', models.BooleanField(default=True)),
                ('show_uuid', models.BooleanField(default=True)),
                ('show_status', models.BooleanField(default=True)),
                ('show_discount', models.BooleanField(default=True)),
                ('income_template', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '格式配置',
                'verbose_name_plural': '格式配置',
                'constraints': [models.UniqueConstraint(fields=('owner',), name='unique_user_config')],
            },
        ),
    ]
