# Generated by Django 4.1.1 on 2023-05-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_map_payee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8, unique=True)),
                ('payee', models.CharField(max_length=8)),
                ('expend', models.CharField(default='Expenses:Other', max_length=64)),
                ('tag', models.CharField(max_length=16)),
                ('classification', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
