# Generated by Django 4.1.1 on 2023-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0006_expense_map_delete_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8, unique=True)),
                ('income', models.CharField(default='Income:Other', max_length=64)),
            ],
        ),
    ]
