# Generated by Django 4.1.1 on 2023-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0007_income_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_map',
            name='full',
            field=models.CharField(default=False, max_length=8),
        ),
    ]
