# Generated by Django 4.1.1 on 2023-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('translate', '0008_income_map_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8, unique=True)),
                ('full', models.CharField(max_length=8)),
                ('income', models.CharField(default='Income:Other', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Income_Map',
        ),
    ]
