# Generated by Django 4.1.1 on 2023-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0009_assets_map_delete_income_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets_map',
            name='full',
            field=models.CharField(max_length=16),
        ),
    ]
