# Generated by Django 5.1.7 on 2025-03-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0011_remove_assets_currency_expense_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formatconfig',
            options={'verbose_name': '格式化输出', 'verbose_name_plural': '格式化输出'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.CharField(help_text='收款方', max_length=32, null=True),
        ),
    ]
