# Generated by Django 4.2.1 on 2023-06-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('translate', '0011_expense_map_payee_order_alter_assets_map_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense_map',
            options={'verbose_name': '支出映射', 'verbose_name_plural': '支出映射'},
        ),
        migrations.AlterField(
            model_name='expense_map',
            name='key',
            field=models.CharField(help_text='关键字', max_length=16, unique=True),
        ),
        migrations.AlterModelTable(
            name='expense_map',
            table='translate_expense_map',
        ),
    ]
