# Generated by Django 5.1.4 on 2025-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0012_alter_formatconfig_options_alter_expense_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='enable',
            field=models.BooleanField(default=True, help_text='启用状态', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='expense',
            name='enable',
            field=models.BooleanField(default=True, help_text='启用状态', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='income',
            name='enable',
            field=models.BooleanField(default=True, help_text='启用状态', verbose_name='是否启用'),
        ),
    ]
