# Generated by Django 4.2.1 on 2023-06-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0012_delete_file_delete_mycmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='MyCmodel',
        ),
    ]
