# Generated by Django 5.1.4 on 2025-10-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sms_2fa_enabled',
            field=models.BooleanField(default=False, help_text='是否启用基于短信的双因素认证', verbose_name='启用SMS双因素认证'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_device_id',
            field=models.IntegerField(blank=True, help_text='关联的TOTP设备ID（django-otp）', null=True, verbose_name='TOTP设备ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='是否启用基于时间的一次性密码（TOTP）双因素认证', verbose_name='启用TOTP双因素认证'),
        ),
    ]
