# Generated by Django 6.0.5 on 2026-09-15 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_sms_2fa_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='便于用户识别的用途说明，如 Claude Code', max_length=64, verbose_name='名称')),
                ('prefix', models.CharField(help_text='明文前缀，用于按前缀定位令牌记录', max_length=16, unique=True, verbose_name='令牌前缀')),
                ('token_hash', models.CharField(help_text='SHA-256 摘要，明文不落库', max_length=64, unique=True, verbose_name='令牌摘要')),
                ('scopes', models.CharField(default='ledger:read', help_text='空格分隔的 scope 列表', max_length=200, verbose_name='权限范围')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_access_tokens', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人访问令牌',
                'verbose_name_plural': '个人访问令牌',
                'db_table': 'personal_access_token',
                'ordering': ['-created'],
            },
        ),
    ]
