# Generated by Django 5.2.1 on 2025-05-23 03:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='关键字', max_length=16)),
                ('full', models.CharField(help_text='账户名称', max_length=16)),
                ('assets', models.CharField(default='Assets:Other:Test', help_text='资产账户', max_length=64)),
                ('enable', models.BooleanField(default=True, help_text='启用状态', verbose_name='是否启用')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资产映射',
                'verbose_name_plural': '资产映射',
                'db_table': 'maps_assets',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='关键字', max_length=16)),
                ('payee', models.CharField(help_text='收款方', max_length=32, null=True)),
                ('expend', models.CharField(default='Expenses:Other', help_text='支出账户', max_length=64)),
                ('currency', models.CharField(help_text='货币', max_length=24, null=True, validators=[django.core.validators.RegexValidator(message="货币必须以大写字母开头，以大写字母/数字结尾，并且只能包含 [A-Z0-9'._-]", regex="^[A-Z][A-Z0-9\\'._-]{0,22}([A-Z0-9])?$")])),
                ('enable', models.BooleanField(default=True, help_text='启用状态', verbose_name='是否启用')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '支出映射',
                'verbose_name_plural': '支出映射',
                'db_table': 'maps_expense',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='关键字', max_length=16)),
                ('payer', models.CharField(help_text='付款方', max_length=8, null=True)),
                ('income', models.CharField(default='Income:Other', help_text='收入账户', max_length=64)),
                ('enable', models.BooleanField(default=True, help_text='启用状态', verbose_name='是否启用')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收入映射',
                'verbose_name_plural': '收入映射',
                'db_table': 'maps_income',
            },
        ),
    ]
