# Generated by Django 5.1.4 on 2025-08-26 00:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='模板名称', max_length=32)),
                ('description', models.TextField(blank=True, help_text='模板描述')),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入'), ('assets', '资产')], help_text='模板类型', max_length=16)),
                ('is_public', models.BooleanField(default=False, help_text='是否公开')),
                ('is_official', models.BooleanField(default=False, help_text='是否官方')),
                ('version', models.CharField(blank=True, default='1.0.0', help_text='版本号', max_length=16)),
                ('update_notes', models.TextField(blank=True, help_text='更新说明', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '映射模板',
                'verbose_name_plural': '映射模板',
                'db_table': 'maps_template',
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='关键字', max_length=16)),
                ('account', models.CharField(help_text='映射账户', max_length=64)),
                ('payee', models.CharField(blank=True, help_text='收款方', max_length=32, null=True)),
                ('payer', models.CharField(blank=True, help_text='付款方', max_length=32, null=True)),
                ('full', models.CharField(blank=True, help_text='账户全称', max_length=32, null=True)),
                ('currency', models.CharField(blank=True, help_text='货币', max_length=24, null=True, validators=[django.core.validators.RegexValidator(message="货币必须以大写字母开头，以大写字母/数字结尾，并且只能包含 [A-Z0-9'._-]", regex="^[A-Z][A-Z0-9\\'._-]{0,22}([A-Z0-9])?$")])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maps.template')),
            ],
            options={
                'verbose_name': '模板项',
                'verbose_name_plural': '模板项',
                'db_table': 'maps_template_item',
            },
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'type'), name='unique_template_per_user_type'),
        ),
        migrations.AddConstraint(
            model_name='templateitem',
            constraint=models.UniqueConstraint(fields=('template', 'key'), name='unique_key_per_template'),
        ),
    ]
