# Generated by Django 5.1.4 on 2025-09-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0002_currency_alter_account_options_and_more'),
        ('maps', '0002_template_templateitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='currency',
        ),
        migrations.AddField(
            model_name='assets',
            name='currencies',
            field=models.ManyToManyField(blank=True, help_text='货币', to='account_config.currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currencies',
            field=models.ManyToManyField(blank=True, help_text='货币', to='account_config.currency'),
        ),
        migrations.AddField(
            model_name='income',
            name='currencies',
            field=models.ManyToManyField(blank=True, help_text='货币', to='account_config.currency'),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='currencies',
            field=models.ManyToManyField(blank=True, help_text='货币', to='account_config.currency'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets',
            field=models.ForeignKey(help_text='资产账户', on_delete=django.db.models.deletion.CASCADE, to='account_config.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expend',
            field=models.ForeignKey(help_text='支出账户', on_delete=django.db.models.deletion.CASCADE, to='account_config.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.CharField(blank=True, help_text='收款方', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.ForeignKey(help_text='收入账户', on_delete=django.db.models.deletion.CASCADE, to='account_config.account'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payer',
            field=models.CharField(blank=True, help_text='付款方', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='account',
            field=models.ForeignKey(help_text='映射账户', on_delete=django.db.models.deletion.CASCADE, to='account_config.account'),
        ),
    ]
