# Generated by Django 5.1.4 on 2025-09-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0002_currency_alter_account_options_and_more'),
        ('maps', '0003_remove_expense_currency_remove_templateitem_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='income',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='currencies',
        ),
        migrations.AddField(
            model_name='assets',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='货币', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='货币', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.currency'),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='货币', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.currency'),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='货币', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.currency'),
        ),
    ]
