# Generated by Django 5.1.4 on 2025-09-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_remove_assets_currencies_remove_expense_currencies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='income',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='currency',
        ),
    ]
