# Generated by Django 5.1.4 on 2025-09-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0003_currency_owner_alter_currency_code_and_more'),
        ('maps', '0005_remove_assets_currency_remove_income_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitem',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='货币', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.currency'),
        ),
    ]
