# Generated by Django 5.1.4 on 2025-10-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0003_currency_owner_alter_currency_code_and_more'),
        ('maps', '0006_templateitem_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expend',
            field=models.ForeignKey(blank=True, help_text='支出账户', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.account'),
        ),
    ]
