# Generated by Django 5.1.4 on 2025-10-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0003_currency_owner_alter_currency_code_and_more'),
        ('maps', '0007_alter_expense_expend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets',
            field=models.ForeignKey(blank=True, help_text='资产账户', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.account'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.ForeignKey(blank=True, help_text='收入账户', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.account'),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='account',
            field=models.ForeignKey(blank=True, help_text='映射账户', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_config.account'),
        ),
    ]
