# Generated by Django 5.1.4 on 2025-10-07 08:06

from django.db import migrations, models


def convert_currency_fk_to_string(apps, schema_editor):
    """将currency外键转换为字符串"""
    # Currency表已经不存在了，需要使用原始SQL
    # 如果currency_id字段存在且有值，我们将其设置为'CNY'作为默认值
    # 因为无法再获取原来的货币代码

    # 检查currency_id列是否存在
    with schema_editor.connection.cursor() as cursor:
        # 检查maps_expense表是否有currency_id列
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='maps_expense' AND column_name='currency_id'
        """)
        expense_has_currency_id = cursor.fetchone() is not None

        if expense_has_currency_id:
            # 将有currency_id的记录设置currency_temp为'CNY'
            cursor.execute("""
                UPDATE maps_expense 
                SET currency_temp = 'CNY' 
                WHERE currency_id IS NOT NULL
            """)

        # 检查maps_template_item表是否有currency_id列
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='maps_template_item' AND column_name='currency_id'
        """)
        item_has_currency_id = cursor.fetchone() is not None

        if item_has_currency_id:
            # 将有currency_id的记录设置currency_temp为'CNY'
            cursor.execute("""
                UPDATE maps_template_item 
                SET currency_temp = 'CNY' 
                WHERE currency_id IS NOT NULL
            """)


def reverse_convert_currency(apps, schema_editor):
    """回滚操作 - 不需要实现，因为无法从字符串恢复外键关系"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_alter_assets_assets_alter_income_income_and_more'),
        ('account_config', '0003_currency_owner_alter_currency_code_and_more'),
    ]

    operations = [
        # 步骤1: 添加临时字段
        migrations.AddField(
            model_name='expense',
            name='currency_temp',
            field=models.CharField(blank=True, help_text='货币代码', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='currency_temp',
            field=models.CharField(blank=True, help_text='货币代码', max_length=24, null=True),
        ),
        # 步骤2: 数据迁移
        migrations.RunPython(convert_currency_fk_to_string, reverse_convert_currency),
        # 步骤3: 删除外键字段
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='currency',
        ),
        # 步骤4: 将临时字段重命名为currency
        migrations.RenameField(
            model_name='expense',
            old_name='currency_temp',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='templateitem',
            old_name='currency_temp',
            new_name='currency',
        ),
    ]

