# Generated by Django 5.1.4 on 2025-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_convert_currency_to_charfield'),
        ('tags', '0002_alter_tag_created_alter_tag_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='关联标签', related_name='assets_mappings', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='关联标签', related_name='expense_mappings', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='income',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='关联标签', related_name='income_mappings', to='tags.tag'),
        ),
    ]
