# Generated by Django migration

from django.db import migrations, models


def convert_account_fk_to_string(apps, schema_editor):
    """将TemplateItem的account外键转换为账户路径字符串"""
    TemplateItem = apps.get_model('maps', 'TemplateItem')
    Account = apps.get_model('account_config', 'Account')
    
    # 遍历所有模板项，将account外键转换为账户路径字符串
    for item in TemplateItem.objects.all():
        if item.account_id:  # 如果有关联的账户
            try:
                account = Account.objects.get(id=item.account_id)
                # 将账户路径存储到临时字段
                item.account_temp = account.account
            except Account.DoesNotExist:
                # 如果账户不存在，设置为None
                item.account_temp = None
        else:
            # 如果原本就是None，保持为None
            item.account_temp = None
        item.save(update_fields=['account_temp'])


def reverse_convert_account(apps, schema_editor):
    """回滚操作 - 不需要实现，因为无法从字符串恢复外键关系"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_assets_tags_expense_tags_income_tags'),
        ('account', '0001_initial'),  # 确保Account模型存在
    ]

    operations = [
        # 步骤1: 添加临时字段
        migrations.AddField(
            model_name='templateitem',
            name='account_temp',
            field=models.CharField(blank=True, help_text='映射账户路径', max_length=128, null=True),
        ),
        # 步骤2: 数据迁移
        migrations.RunPython(convert_account_fk_to_string, reverse_convert_account),
        # 步骤3: 删除外键字段
        migrations.RemoveField(
            model_name='templateitem',
            name='account',
        ),
        # 步骤4: 将临时字段重命名为account
        migrations.RenameField(
            model_name='templateitem',
            old_name='account_temp',
            new_name='account',
        ),
    ]

