# Generated by Django 5.1.4 on 2026-01-13 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_config', '0005_remove_account_currencies_accounttemplate_and_more'),
        ('maps', '0011_convert_templateitem_account_to_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets',
            field=models.ForeignKey(blank=True, help_text='资产账户', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_config.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expend',
            field=models.ForeignKey(blank=True, help_text='支出账户', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_config.account'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.ForeignKey(blank=True, help_text='收入账户', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_config.account'),
        ),
    ]
