# Generated by Django 6.0.5 on 2026-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_alter_assets_assets_alter_expense_expend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitem',
            name='tag_paths',
            field=models.JSONField(blank=True, default=list, help_text='关联标签路径列表'),
        ),
    ]
