# Generated by Django 6.0.5 on 2026-06-15 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_created_alter_tag_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='模板名称', max_length=32)),
                ('description', models.TextField(blank=True, help_text='模板描述')),
                ('is_public', models.BooleanField(default=False, help_text='是否公开')),
                ('is_official', models.BooleanField(default=False, help_text='是否官方')),
                ('version', models.CharField(blank=True, default='1.0.0', help_text='版本号', max_length=16)),
                ('update_notes', models.TextField(blank=True, help_text='更新说明', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '标签模板',
                'verbose_name_plural': '标签模板',
                'db_table': 'tags_tag_template',
            },
        ),
        migrations.CreateModel(
            name='TagTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tag_path', models.CharField(help_text='标签完整路径', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='标签描述')),
                ('enable', models.BooleanField(default=True, help_text='默认启用状态')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tags.tagtemplate')),
            ],
            options={
                'verbose_name': '标签模板项',
                'verbose_name_plural': '标签模板项',
                'db_table': 'tags_tag_template_item',
            },
        ),
        migrations.AddConstraint(
            model_name='tagtemplate',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_tag_template_per_user'),
        ),
        migrations.AddConstraint(
            model_name='tagtemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'tag_path'), name='unique_tag_path_per_template'),
        ),
    ]
