# Generated by Django 5.2.1 on 2025-05-23 03:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(default='*', max_length=1)),
                ('show_note', models.BooleanField(default=True)),
                ('show_tag', models.BooleanField(default=True)),
                ('show_time', models.BooleanField(default=True)),
                ('show_uuid', models.BooleanField(default=True)),
                ('show_status', models.BooleanField(default=True)),
                ('show_discount', models.BooleanField(default=True)),
                ('income_template', models.CharField(blank=True, default='Income:Discount', max_length=50, null=True)),
                ('commission_template', models.CharField(blank=True, default='Expenses:Finance:Commission', max_length=50, null=True)),
                ('currency', models.CharField(default='CNY', max_length=24, validators=[django.core.validators.RegexValidator(message="货币必须以大写字母开头，以大写字母/数字结尾，并且只能包含 [A-Z0-9'._-]", regex="^[A-Z][A-Z0-9\\'._-]{0,22}([A-Z0-9])?$")])),
                ('ai_model', models.CharField(default='bert', help_text='AI模型', max_length=16)),
                ('deepseek_apikey', models.CharField(blank=True, help_text='DeepSeek API密钥', max_length=128, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '格式化输出',
                'verbose_name_plural': '格式化输出',
                'constraints': [models.UniqueConstraint(fields=('owner',), name='unique_user_config')],
            },
        ),
    ]
