# Generated by Django 5.1.4 on 2025-08-07 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_rename_minio_path_file_storage_name'),
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unprocessed', '未解析'), ('pending', '待解析'), ('processing', '解析中'), ('success', '解析成功'), ('failed', '解析失败')], default='unprocessed', max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.file')),
            ],
        ),
    ]
