# Generated by Django 5.1.4 on 2025-08-09 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_rename_minio_path_file_storage_name'),
        ('translate', '0002_parsefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsefile',
            name='id',
        ),
        migrations.AddField(
            model_name='parsefile',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsefile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='file_manager.file'),
        ),
    ]
