# Generated by Django 4.2.3 on 2023-12-02 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate', '0003_remove_expense_payee_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': '资产映射', 'verbose_name_plural': '资产映射'},
        ),
        migrations.RemoveField(
            model_name='assets',
            name='income',
        ),
        migrations.AddField(
            model_name='assets',
            name='assets',
            field=models.CharField(default='Assets:Other:Test', help_text='资产账户', max_length=64),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.CharField(help_text='收款方', max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='关键字', max_length=16)),
                ('payer', models.CharField(help_text='付款方', max_length=8, null=True)),
                ('income', models.CharField(default='Income:Other', help_text='收入账户', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income',
                                            to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收入映射',
                'verbose_name_plural': '收入映射',
                'db_table': 'maps_income',
            },
        ),
    ]
