# Generated by Django 5.1.4 on 2025-08-09 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_rename_minio_path_file_storage_name'),
        ('translate', '0003_remove_parsefile_id_parsefile_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsefile',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='file_manager.file'),
        ),
    ]
