# Generated by Django 5.1.4 on 2025-09-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_alter_parsefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatconfig',
            name='ai_model',
            field=models.CharField(default='BERT', help_text='AI模型', max_length=16),
        ),
    ]
