# Generated by Django 4.2.3 on 2023-12-02 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('translate', '0004_alter_assets_options_remove_assets_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tag',
        ),
    ]
