# Generated by Django 5.1.4 on 2025-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_alter_formatconfig_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsefile',
            name='status',
            field=models.CharField(choices=[('unprocessed', '未解析'), ('pending', '待解析'), ('processing', '解析中'), ('parsed', '已解析'), ('failed', '解析失败'), ('cancelled', '取消解析')], default='unprocessed', max_length=20),
        ),
    ]
