# Generated by Django 5.2.10 on 2026-02-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0006_alter_parsefile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatconfig',
            name='parsing_mode_preference',
            field=models.CharField(choices=[('review', '审核模式'), ('direct_write', '直接写入模式')], default='review', help_text='解析模式偏好：审核模式需要用户审核后再写入，直接写入模式解析后立即写入', max_length=16),
        ),
        migrations.AlterField(
            model_name='parsefile',
            name='status',
            field=models.CharField(choices=[('unprocessed', '未解析'), ('pending', '待解析'), ('processing', '解析中'), ('pending_review', '待审核'), ('parsed', '已解析'), ('failed', '解析失败'), ('cancelled', '取消解析')], default='unprocessed', max_length=20),
        ),
    ]
