# Generated by Django 5.1.7 on 2025-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0007_formatconfig_commission_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatconfig',
            name='commission_template',
            field=models.CharField(blank=True, default='Expenses:Finance:Commission', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formatconfig',
            name='income_template',
            field=models.CharField(blank=True, default='Income:Discount', max_length=50, null=True),
        ),
    ]
