# Generated by Django 6.0.5 on 2026-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0007_formatconfig_parsing_mode_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatconfig',
            name='reconciliation_fallback_account',
            field=models.CharField(
                blank=True,
                default='Equity:Adjustments',
                help_text='非首次对账时差额分配的默认兜底账户',
                max_length=128,
                null=True
            ),
        ),
    ]
