# Generated by Django 6.0.5 on 2026-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0008_formatconfig_reconciliation_fallback_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatconfig',
            name='income_template',
            field=models.CharField(blank=True, default='Income:Transfer:Organizational', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formatconfig',
            name='reconciliation_fallback_account',
            field=models.CharField(blank=True, default='Equity:Adjustments', help_text='无法匹配资产账户时的默认兜底账户，也用于非首次对账差额分配', max_length=128, null=True),
        ),
    ]
