# Generated by Django 5.1.4 on 2025-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0013_assets_enable_expense_enable_income_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatconfig',
            name='ai_model',
            field=models.CharField(default='BERT', help_text='AI模型', max_length=16),
        ),
        migrations.AddField(
            model_name='formatconfig',
            name='deepseek_apikey',
            field=models.CharField(blank=True, help_text='DeepSeek API密钥', max_length=128, null=True),
        ),
    ]
