# Generated by Django 5.2.1 on 2025-06-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='minio_path',
            new_name='storage_name',
        ),
    ]
