# Generated by Django 5.2.1 on 2025-06-05 00:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billfile',
            name='file_manage_user_id_8d7de2_idx',
        ),
        migrations.RemoveField(
            model_name='billfile',
            name='user',
        ),
        migrations.AddField(
            model_name='billfile',
            name='owner',
            field=models.ForeignKey(default=1, help_text='文件所有者', on_delete=django.db.models.deletion.CASCADE, related_name='billfile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billfile',
            name='file_size',
            field=models.PositiveIntegerField(help_text='文件大小（字节）'),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='文件唯一标识符', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否启用，软删除标志'),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='original_name',
            field=models.CharField(help_text='原始文件名', max_length=255),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='storage_path',
            field=models.CharField(help_text='minIO存储路径', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='billfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='上传时间'),
        ),
        migrations.AddIndex(
            model_name='billfile',
            index=models.Index(fields=['owner', 'uploaded_at'], name='file_manage_owner_i_982daa_idx'),
        ),
    ]
