# Generated by Django 5.2.1 on 2025-06-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_remove_billfile_file_manage_user_id_8d7de2_idx_and_more'),
    ]

    operations = [
    ]
