# Generated by Django 4.1.1 on 2023-04-12 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 2, 51, 12, 486930)),
        ),
    ]
