# Generated by Django 4.1.1 on 2023-04-12 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0002_alter_users_addtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='addtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
