# Generated by Django 5.2.1 on 2025-06-16 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavaInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, max_length=64)),
                ('container_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('error', 'Error')], default='stopped', max_length=20)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
