# Generated by Django 5.2.1 on 2025-06-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fava_instances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favainstance',
            options={'verbose_name': 'Fava 实例', 'verbose_name_plural': 'Fava 实例'},
        ),
        migrations.AlterModelTable(
            name='favainstance',
            table='fava_instances',
        ),
    ]
