# Generated by Django 4.2.3 on 2023-10-22 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='日期', max_length=16, verbose_name='日期')),
                ('status',
                 models.CharField(choices=[('open', 'open'), ('close', 'close')], help_text='状态', max_length=8,
                                  verbose_name='状态')),
                ('account', models.CharField(help_text='账户', max_length=64, verbose_name='账户')),
                ('currency', models.CharField(help_text='货币', max_length=16, null=True, verbose_name='货币')),
                ('note', models.CharField(help_text='备注', max_length=16, null=True, verbose_name='备注')),
                ('account_type', models.CharField(
                    choices=[('assets', '资产账户'), ('equity', '平衡账户'), ('expenses', '支出账户'),
                             ('income', '收入账户'), ('Liabilities', '负债账户')], max_length=16,
                    verbose_name='交易类型')),
                ('owner', models.ForeignKey(help_text='属主', on_delete=django.db.models.deletion.CASCADE,
                                            related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='属主')),
            ],
            options={
                'verbose_name': '所有账户',
                'verbose_name_plural': '所有账户',
                'ordering': ['account_type'],
            },
        ),
    ]
