# Generated by Django 5.1.4 on 2026-01-21 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('reconciliation', '对账'), ('ai_feedback', 'AI 反馈确认')], max_length=32, verbose_name='任务类型')),
                ('object_id', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField(verbose_name='预期执行日期')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '待办任务',
                'verbose_name_plural': '待办任务',
                'db_table': 'scheduled_task',
                'indexes': [models.Index(fields=['task_type', 'status', 'scheduled_date'], name='scheduled_t_task_ty_e73322_idx'), models.Index(fields=['content_type', 'object_id'], name='scheduled_t_content_70a96b_idx')],
            },
        ),
    ]
