# Generated by Django 5.2.10 on 2026-01-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='as_of_date',
            field=models.DateField(blank=True, null=True, verbose_name='账本对账日期'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['task_type', 'content_type', 'object_id', 'as_of_date', 'status'], name='scheduled_t_task_ty_553dc2_idx'),
        ),
    ]
