# Generated by Django 5.2.10 on 2026-02-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_scheduledtask_as_of_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='预期执行日期'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('inactive', '未激活'), ('pending', '待执行'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('reconciliation', '对账'), ('parse_review', '解析审核')], max_length=32, verbose_name='任务类型'),
        ),
    ]
