# Generated by Django 5.2.10 on 2026-03-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_alter_scheduledtask_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='reconciliation_entries',
            field=models.JSONField(blank=True, null=True, verbose_name='对账条目'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('inactive', '未激活'), ('pending', '待执行'), ('completed', '已完成'), ('cancelled', '已取消'), ('revoked', '已撤销')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
