# Generated by Django 5.2.10 on 2026-03-10 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_alter_scheduledtask_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='reconciliation_entries',
            field=models.JSONField(blank=True, null=True, verbose_name='对账条目'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='reconciliation_transaction_items',
            field=models.JSONField(blank=True, null=True, verbose_name='对账差额分配条目'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='revoked_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_task_follow_ups', to='reconciliation.scheduledtask', verbose_name='被撤销的对账任务'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('inactive', '未激活'), ('pending', '待执行'), ('completed', '已完成'), ('cancelled', '已取消'), ('revoked', '已撤销')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
