# Generated by Django 6.0.5 on 2026-09-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_scheduledtask_reconciliation_entries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('reconciliation', '对账'), ('parse_review', '解析审核'), ('entry_review', '条目审核')], max_length=32, verbose_name='任务类型'),
        ),
    ]
