"""collect.bean 系统账本功能测试

覆盖：
- BeanFileManager.get_collect_bean_path 路径拼接
- BeanFileManager.ensure_collect_bean 创建 / 幂等 / 不覆盖已有内容
- BeanFileManager.append_to_collect_bean 追加语义 / 空输入不写入
- BeanFileManager.init_user_bean_structure 在用户创建时接入 collect.bean
- 管理命令 ensure_collect_bean（首次补齐 / 幂等 / --dry-run / --user）

所有测试将 settings.ASSETS_BASE_PATH 指向 tmp_path，避免污染真实 Assets 目录。
"""
import io
import os
from pathlib import Path

import pytest
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management import call_command

from project.utils.file import BeanFileManager

User = get_user_model()

pytestmark = pytest.mark.django_db

COLLECT_HEADER = (
    "; Trans directory - Auto-generated includes\n"
    "; This file is automatically generated by the platform\n\n"
)
COLLECT_INCLUDE = 'include "collect.bean"'


@pytest.fixture
def assets_dir(tmp_path, monkeypatch):
    """把 ASSETS_BASE_PATH 指向临时目录，隔离文件系统。"""
    base = tmp_path / 'Assets'
    base.mkdir()
    monkeypatch.setattr(settings, 'ASSETS_BASE_PATH', str(base))
    return base


@pytest.fixture
def user(assets_dir):
    return User.objects.create_user(username='collectuser', password='testpass123')


def _collect_path(user_or_username):
    return Path(BeanFileManager.get_collect_bean_path(user_or_username))


def _collect_text(user):
    return _collect_path(user).read_text(encoding='utf-8')


def _main_text(user):
    return Path(BeanFileManager.get_trans_main_bean_path(user)).read_text(encoding='utf-8')


def _include_lines(user):
    return [
        line.strip()
        for line in _main_text(user).splitlines()
        if line.strip().startswith('include ')
    ]


def _remove_include_line(user, include_line):
    """从 trans/main.bean 中删除指定 include 行（用于模拟存量用户）。"""
    path = Path(BeanFileManager.get_trans_main_bean_path(user))
    lines = [
        line
        for line in path.read_text(encoding='utf-8').splitlines(keepends=True)
        if line.strip() != include_line
    ]
    path.write_text(''.join(lines), encoding='utf-8')


def _reset_to_legacy(user):
    """删除 collect.bean 及其 include 行，模拟尚未补齐的存量用户。"""
    _collect_path(user).unlink()
    _remove_include_line(user, COLLECT_INCLUDE)


def _run_command(**kwargs):
    out = io.StringIO()
    call_command('ensure_collect_bean', stdout=out, **kwargs)
    return out.getvalue()


# --------------------------------------------------------------------------- #
# get_collect_bean_path
# --------------------------------------------------------------------------- #
class TestGetCollectBeanPath:
    def test_matches_assets_layout(self, user, assets_dir):
        expected = os.path.join(str(assets_dir), user.username, 'trans', 'collect.bean')

        assert BeanFileManager.get_collect_bean_path(user) == expected

    def test_accepts_username_string(self, assets_dir):
        expected = os.path.join(str(assets_dir), 'someone', 'trans', 'collect.bean')

        assert BeanFileManager.get_collect_bean_path('someone') == expected


# --------------------------------------------------------------------------- #
# ensure_collect_bean
# --------------------------------------------------------------------------- #
class TestEnsureCollectBean:
    def test_creates_file_with_header_and_single_include(self, user):
        _reset_to_legacy(user)
        assert not _collect_path(user).exists()
        assert COLLECT_INCLUDE not in _include_lines(user)

        BeanFileManager.ensure_collect_bean(user)

        assert _collect_path(user).is_file()
        assert _collect_text(user) == COLLECT_HEADER
        assert _include_lines(user).count(COLLECT_INCLUDE) == 1

    def test_is_idempotent(self, user):
        BeanFileManager.ensure_collect_bean(user)
        content_after_first = _collect_text(user)
        includes_after_first = list(_include_lines(user))

        BeanFileManager.ensure_collect_bean(user)

        assert _collect_text(user) == content_after_first
        assert _include_lines(user) == includes_after_first
        assert _include_lines(user).count(COLLECT_INCLUDE) == 1

    def test_does_not_overwrite_existing_content(self, user):
        custom = (
            '2025-01-20 * "自定义条目" "保留我"\n'
            '  Assets:Test                100.00 CNY\n'
            '  Expenses:Test             -100.00 CNY\n'
        )
        _collect_path(user).write_text(custom, encoding='utf-8')

        BeanFileManager.ensure_collect_bean(user)

        assert _collect_text(user) == custom
        assert '自定义条目' in _collect_text(user)


# --------------------------------------------------------------------------- #
# append_to_collect_bean
# --------------------------------------------------------------------------- #
class TestAppendToCollectBean:
    def test_first_write_creates_file_with_header_and_directives(self, user):
        _reset_to_legacy(user)
        d1 = '2025-01-01 * "a" "b"'
        d2 = '2025-01-02 * "c" "d"'

        BeanFileManager.append_to_collect_bean(user, [d1, d2])

        text = _collect_text(user)
        assert text.startswith(COLLECT_HEADER)
        assert text == COLLECT_HEADER + d1 + '\n\n' + d2 + '\n\n'
        assert COLLECT_INCLUDE in _include_lines(user)

    def test_second_write_appends_after_existing_content(self, user):
        BeanFileManager.append_to_collect_bean(user, ['first-1', 'first-2'])
        before = _collect_text(user)

        BeanFileManager.append_to_collect_bean(user, ['second-1'])

        after = _collect_text(user)
        # 原有内容是新内容的前缀，新指令追加在末尾
        assert after.startswith(before)
        assert after == before + 'second-1\n\n'

    @pytest.mark.parametrize('directives', [[], None])
    def test_empty_directives_write_nothing(self, user, directives):
        BeanFileManager.ensure_collect_bean(user)
        baseline = _collect_text(user)
        includes_before = list(_include_lines(user))

        BeanFileManager.append_to_collect_bean(user, directives)

        assert _collect_path(user).is_file()
        assert _collect_text(user) == baseline
        assert _include_lines(user) == includes_before

    def test_empty_directives_still_ensure_missing_file(self, user):
        _reset_to_legacy(user)
        assert not _collect_path(user).exists()

        BeanFileManager.append_to_collect_bean(user, [])

        assert _collect_path(user).is_file()
        assert _collect_text(user) == COLLECT_HEADER
        assert COLLECT_INCLUDE in _include_lines(user)


# --------------------------------------------------------------------------- #
# init_user_bean_structure 接入（用户创建时自动执行）
# --------------------------------------------------------------------------- #
class TestInitUserBeanStructure:
    def test_new_user_gets_collect_bean(self, assets_dir):
        new_user = User.objects.create_user(username='freshuser', password='testpass123')

        expected = os.path.join(
            str(assets_dir), 'freshuser', 'trans', 'collect.bean'
        )
        assert BeanFileManager.get_collect_bean_path(new_user) == expected
        assert _collect_path(new_user).is_file()
        assert _collect_text(new_user).startswith(COLLECT_HEADER)
        assert COLLECT_INCLUDE in _include_lines(new_user)


# --------------------------------------------------------------------------- #
# 管理命令 ensure_collect_bean
# --------------------------------------------------------------------------- #
class TestEnsureCollectBeanCommand:
    def test_creates_collect_bean_for_legacy_user(self, user):
        _reset_to_legacy(user)
        assert not _collect_path(user).exists()

        out = _run_command()

        assert _collect_path(user).is_file()
        assert _collect_text(user) == COLLECT_HEADER
        assert COLLECT_INCLUDE in _include_lines(user)
        assert f'用户 {user.username}: 新建 1 个, 已存在 0 个, 错误 0 个' in out
        assert '=== 补齐完成 ===' in out

    def test_repeated_run_is_idempotent(self, user):
        _reset_to_legacy(user)
        _run_command()
        content_after_first = _collect_text(user)
        main_after_first = _main_text(user)

        out_second = _run_command()

        assert _collect_text(user) == content_after_first
        assert _main_text(user) == main_after_first
        assert _include_lines(user).count(COLLECT_INCLUDE) == 1
        assert f'用户 {user.username}: 新建 0 个, 已存在 1 个, 错误 0 个' in out_second

    def test_user_filter_reports_totals(self, user, assets_dir):
        _reset_to_legacy(user)

        out = _run_command(user=user.username)

        assert _collect_path(user).is_file()
        assert '新建文件数: 1' in out
        assert '已存在文件数: 0' in out

    def test_dry_run_writes_nothing(self, user):
        _reset_to_legacy(user)
        main_before = _main_text(user)

        out = _run_command(dry_run=True)

        assert not _collect_path(user).exists()
        assert _main_text(user) == main_before
        assert COLLECT_INCLUDE not in _include_lines(user)
        assert '模拟运行模式' in out
        assert f'计划创建: {BeanFileManager.get_collect_bean_path(user)}' in out

    def test_user_filter_only_processes_target_user(self, user, assets_dir):
        other = User.objects.create_user(username='otheruser', password='testpass123')
        _reset_to_legacy(user)
        _reset_to_legacy(other)

        out = _run_command(user=user.username)

        assert _collect_path(user).is_file()
        assert COLLECT_INCLUDE in _include_lines(user)
        # 其他用户完全未被处理
        assert not _collect_path(other).exists()
        assert COLLECT_INCLUDE not in _include_lines(other)
        assert other.username not in out
